name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.x'
          cache: npm

      - run: npm ci

      - run: npm test

      - run: npm publish --provenance --access public
